import = [
    "~/.config/alacritty/catpuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"

[window]
#padding = { x = 20, y = 20 }
decorations = "None"
opacity = 0.8
blur = true

[font]
size = 8.0
normal = { family = "ComicShannsMono Nerd Font Propo", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font Propo", style = "Bold" }
italic = { family = "VictorMono Nerd Font Mono", style = "Medium Oblique" }
