[manager]
ratio = [1, 3, 2]
sort_by = "alphabetical"
linemode = "size_and_mtime"
show_hidden = false

[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'vim "$@"', orphan = false, for = "unix", desc = "Open with vim" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open with xdg-open" },
]
opendocppt = [
    { run = 'onlyoffice-desktopeditors "$@"', orphan = true, desc = "Open word documents with Only Office" },
]
pdf = [
    { run = 'zathura "$0"', orphan = true, desc = "Open pdf files with zathura" }
]

[open]
rules = [
    { name = "*.txt", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = "*.docx", use = "opendocppt" },
    { name = "*.pdf", use = "pdf" },
    { name = "*.pptx", use = "opendocppt" }
]
