[manager]
ratio = [1, 3, 2]
sort_by = "alphabetical"
linemode = "size_and_mtime"
show_hidden = true

[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
word = [
    { run = 'onlyoffice-desktopeditors "$@"', orphan = true, desc = "Open word documents with Only Office" },
]
pdf = [
    { run = 'zathura "$0"', orphan = true, desc = "Open pdf files with zathura" }
]

[open]
rules = [
    { name = "*.docx", use = "word" },
    { name = "*.pdf", use = "pdf" }
]
