[colors]
foreground = "#e0e0e0"
background = "#0a0a0f"
cursor_bg = "#ff00ff"
cursor_border = "#ff00ff"
cursor_fg = "#ffffff"
selection_bg = "#3a3a4d"
selection_fg = "#ffffff"

ansi = ["#1a1a2e", "#ff0055", "#00ff99", "#ffaa00", "#00aaff", "#aa00ff", "#00ffff", "#d0d0d0"]
brights = ["#4a4a6a", "#ff5599", "#88ffbb", "#ffcc66", "#66ccff", "#cc66ff", "#99ffff", "#ffffff"]

[colors.tab_bar]
background = "#0f0f1a"
active_tab = { bg_color = "#3a3a4d", fg_color = "#ffffff" }
inactive_tab = { bg_color = "#1a1a2e", fg_color = "#808080" }
inactive_tab_hover = { bg_color = "#2a2a3d", fg_color = "#c0c0c0" }

[colors.indexed]
16 = "#ff00aa"
17 = "#aa00ff"
18 = "#0055ff"
19 = "#55ffff"
20 = "#ff55aa"
21 = "#5500ff"
