import = [
    "~/dotfiles/.config/alacritty/tokyonight.toml"
]

[shell]
program = "/bin/zsh"

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.8
blur = true

[font]
size = 12
normal = { family = "BerkeleyMono Nerd Font Mono", style = "Regular"}
bold = { family = "BerkeleyMono Nerd Font Mono", style = "Bold"}
italic = { family = "BerkeleyMono Nerd Font Mono", style = "Italic"}
bold_italic = { family = "BerkeleyMono Nerd Font Mono", style = "Bold Italic"}
